from sqlalchemy import Column, Integer, String, Text, Float, DateTime, ForeignKey, JSON, BigInteger, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from .database import Base


class Project(Base):
    """A project containing RFIs, submittals, and specification files"""
    __tablename__ = "projects"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    rfi_folder_path = Column(String(1024), nullable=False)  # Also used for submittals
    specs_folder_path = Column(String(1024), nullable=False)
    created_date = Column(DateTime(timezone=True), server_default=func.now())
    last_scanned = Column(DateTime(timezone=True), nullable=True)
    
    # Exclude folders from spec suggestions (JSON list of folder names/paths)
    exclude_folders = Column(JSON, nullable=True, default=list)
    # Must-include folders for Smart Analysis (JSON list of folder names/paths)
    include_folders = Column(JSON, nullable=True, default=list)

    # Knowledge base status
    kb_indexed = Column(Boolean, default=False)  # Whether specs are indexed in vector store
    kb_last_indexed = Column(DateTime(timezone=True), nullable=True)
    kb_document_count = Column(Integer, default=0)  # Number of chunks in vector store

    # Relationships
    files = relationship("ProjectFile", back_populates="project", cascade="all, delete-orphan")
    results = relationship("ProcessingResult", back_populates="project", cascade="all, delete-orphan")


class ProjectFile(Base):
    """An indexed file within a project (RFI, submittal, spec, drawing, etc.)"""
    __tablename__ = "project_files"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=False)

    # File info
    file_path = Column(String(1024), nullable=False)  # Absolute path
    filename = Column(String(255), nullable=False)
    file_type = Column(String(50), nullable=False)  # pdf, docx, dwg, dxf, png, jpg, etc.
    file_size = Column(BigInteger, nullable=False)
    modified_date = Column(DateTime(timezone=True), nullable=False)
    last_indexed = Column(DateTime(timezone=True), nullable=True)

    # Content classification
    # rfi, submittal, specification, drawing, image, other
    content_type = Column(String(50), nullable=False)

    # Extracted content
    content_text = Column(Text, nullable=True)  # Extracted text content
    file_metadata = Column(JSON, nullable=True)  # File-specific metadata (layers, pages, dimensions, etc.)

    # Knowledge base indexing
    kb_indexed = Column(Boolean, default=False)  # Whether this file is in the vector store
    kb_chunk_count = Column(Integer, default=0)  # Number of chunks in vector store

    # Relationships
    project = relationship("Project", back_populates="files")
    processing_results = relationship("ProcessingResult", back_populates="source_file",
                                      foreign_keys="ProcessingResult.source_file_id")


class ProcessingResult(Base):
    """
    Result of processing an RFI or Submittal against specifications.

    For RFIs: Provides informational response with spec references (no status)
    For Submittals: Provides review with status (No Exceptions, Revise & Resubmit, etc.)
    """
    __tablename__ = "processing_results"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=False)
    source_file_id = Column(Integer, ForeignKey("project_files.id"), nullable=True)  # Nullable for path-based analysis

    # For path-based Smart Analysis (no database file record)
    source_filename = Column(String(255), nullable=True)  # Filename for path-based results
    source_file_path = Column(String(1024), nullable=True)  # Full path for path-based results

    # Document type determines response format
    document_type = Column(String(50), nullable=False)  # rfi, submittal

    # Response content (generated by AI)
    response_text = Column(Text, nullable=True)  # The generated response/review

    # Submittal-specific: Review status (null for RFIs)
    # no_exceptions, revise_and_resubmit, rejected, approved_as_noted, see_comments
    status = Column(String(50), nullable=True)

    # Analysis metadata
    consultant_type = Column(String(100), nullable=True)  # structural, electrical, mechanical, etc.
    confidence = Column(Float, nullable=False, default=0.0)
    processed_date = Column(DateTime(timezone=True), server_default=func.now())

    # Specification references used in analysis
    # [{source_file_id, source_filename, section, text, score}, ...]
    spec_references = Column(JSON, nullable=True)

    # Relationships
    project = relationship("Project", back_populates="results")
    source_file = relationship("ProjectFile", back_populates="processing_results",
                               foreign_keys=[source_file_id])
